<template>
  <columnwidth size="0" />
  <spaceafter size="0" />
  <color name="black" />
  <style name="regular" />
  <textpos x="0.4" y="4.775" />
  <font name="arial" size="20" />
  <text value="Mix " />
  <color name="red" />
  <style name="bolditalic" />
  <text value="Bumper Crop " />
  <style name="regular" />
  <color name="black" />
  <text value="into your soil for best results!" />
</template>