<template>
  <color name="black" />
  <font name="arial" size="14" />
  <style name="italic" />
  <spaceafter size="0.1" />
  <text prefix="{roundbullet} " value="{topfoldertip1}" />
  <text prefix="{roundbullet} " value="{topfoldertip2}" />
  <text prefix="{roundbullet} " value="{topfoldertip3}" />
  <text prefix="{roundbullet} " value="{topfoldertip4}" />
  <text prefix="{roundbullet} " value="{topfoldertip5}" />
  <text prefix="{roundbullet} " value="{topfoldertip6}" />
  <text prefix="{roundbullet} " value="{topfoldertip7}" />
  <text prefix="{roundbullet} " value="{topfoldertip8}" />
  <text prefix="{roundbullet} " value="{topextratip1}" />
  <text prefix="{roundbullet} " value="{topextratip2}" />
  <text prefix="{roundbullet} " value="{topextratip3}" />
  <text prefix="{roundbullet} " value="{topextratip4}" />
  <text prefix="{roundbullet} " value="{topextratip5}" />
  <text prefix="{roundbullet} " value="{topextratip6}" />
  <text prefix="{roundbullet} " value="{topextratip7}" />
  <text prefix="{roundbullet} " value="{topextratip8}" />
  <text prefix="{roundbullet} " value="{varietytip1}" />
  <text prefix="{roundbullet} " value="{varietytip2}" />
  <text prefix="{roundbullet} " value="{varietytip3}" />
  <text prefix="{roundbullet} " value="{varietytip4}" />
  <text prefix="{roundbullet} " value="{varietytip5}" />
  <text prefix="{roundbullet} " value="{varietytip6}" />
  <text prefix="{roundbullet} " value="{varietytip7}" />
  <text prefix="{roundbullet} " value="{varietytip8}" />
  <text prefix="{roundbullet} " value="{bottomextratip1}" />
  <text prefix="{roundbullet} " value="{bottomextratip2}" />
  <text prefix="{roundbullet} " value="{bottomextratip3}" />
  <text prefix="{roundbullet} " value="{bottomextratip4}" />
  <text prefix="{roundbullet} " value="{bottomextratip5}" />
  <text prefix="{roundbullet} " value="{bottomextratip6}" />
  <text prefix="{roundbullet} " value="{bottomextratip7}" />
  <text prefix="{roundbullet} " value="{bottomextratip8}" />
  <text prefix="{roundbullet} " value="{bottomfoldertip1}" />
  <text prefix="{roundbullet} " value="{bottomfoldertip2}" />
  <text prefix="{roundbullet} " value="{bottomfoldertip3}" />
  <text prefix="{roundbullet} " value="{bottomfoldertip4}" />
  <text prefix="{roundbullet} " value="{bottomfoldertip5}" />
  <text prefix="{roundbullet} " value="{bottomfoldertip6}" />
  <text prefix="{roundbullet} " value="{bottomfoldertip7}" />
  <text prefix="{roundbullet} " value="{bottomfoldertip8}" />
</template>