<template>
  <textpos x="3.4" y="0.125" />
  <columnwidth size="3.5" />
  <font name="arial" size="32" />
  <text center="true" value="{title}" />
  <text center="true" value="{title2}" />
  <font name="arial" size="28" />
  <text center="true" value="{titlesmall}" />
  <text center="true" value="{title2small}" />
  <font name="arial" size="20" />
  <text center="true" value="{subtitle}" />
  <text center="true" value="{subtitle2}" />
  <font name="arial" size="24" />
  <text center="true" value="{variety}" />
  <text center="true" value="{variety2}" />
  <movedown size="0.15" />
</template>